# Generated by Django 3.1.5 on 2021-02-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_usercomment_app_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='app_name',
            new_name='blog_name',
        ),
    ]
