# Generated by Django 3.1.5 on 2021-02-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210210_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='blog_name',
        ),
    ]
