# Generated by Django 3.1.5 on 2021-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_usercomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
