# Generated by Django 3.1.5 on 2021-02-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_usercomment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
    ]
