# Generated by Django 3.1.5 on 2021-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_usercomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='username',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
